// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAabmwZlMDGjG_tMzBZueglPP8ecXtBM6A',
    appId: '1:133154062140:web:066806a0e68d0a77aaa839',
    messagingSenderId: '133154062140',
    projectId: 'appdotroco',
    authDomain: 'appdotroco.firebaseapp.com',
    databaseURL: 'https://appdotroco-default-rtdb.firebaseio.com',
    storageBucket: 'appdotroco.appspot.com',
    measurementId: 'G-SB665R18GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8BsTrs374hbEvlmf4-DE4ZGfAh__FDMM',
    appId: '1:133154062140:android:3b7dcded962043c5aaa839',
    messagingSenderId: '133154062140',
    projectId: 'appdotroco',
    databaseURL: 'https://appdotroco-default-rtdb.firebaseio.com',
    storageBucket: 'appdotroco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFXqT4CRGM7b331JIG1cTrOMK6xoTtxwk',
    appId: '1:133154062140:ios:d504321183394092aaa839',
    messagingSenderId: '133154062140',
    projectId: 'appdotroco',
    databaseURL: 'https://appdotroco-default-rtdb.firebaseio.com',
    storageBucket: 'appdotroco.appspot.com',
    iosBundleId: 'com.example.appTroco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFXqT4CRGM7b331JIG1cTrOMK6xoTtxwk',
    appId: '1:133154062140:ios:d504321183394092aaa839',
    messagingSenderId: '133154062140',
    projectId: 'appdotroco',
    databaseURL: 'https://appdotroco-default-rtdb.firebaseio.com',
    storageBucket: 'appdotroco.appspot.com',
    iosBundleId: 'com.example.appTroco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAabmwZlMDGjG_tMzBZueglPP8ecXtBM6A',
    appId: '1:133154062140:web:61d9724d34817346aaa839',
    messagingSenderId: '133154062140',
    projectId: 'appdotroco',
    authDomain: 'appdotroco.firebaseapp.com',
    databaseURL: 'https://appdotroco-default-rtdb.firebaseio.com',
    storageBucket: 'appdotroco.appspot.com',
    measurementId: 'G-RT5MRPRFBN',
  );
}
